const days=[["01","Arrival & settle in","LOW KEY"],["02","East Kauaʻi • water & discovery","EXPLORE"],["03","Scenic Kauaʻi drive","DISCOVER"],["04","Waimea Canyon","LANDSCAPE"],["05","Different paths • same place","FLEX DAY"],["06","Snorkeling & ocean day","WATER"],["07","Family core-memory day","TOGETHER"],["08","Last morning • goodbye Kauaʻi","SLOW"]];
const timeline=[["Arrival","Airport → Waipouli Beach Resort","Get settled without immediately turning the vacation into a project."],["Afternoon","Groceries + condo setup","Stock the kitchen for the week and make the room feel like home."],["Evening","Easy dinner","Choose convenience over optimization. The island isn't going anywhere."],["Night","First sunset / stargazing","A tiny shared moment to officially begin the trip."]];
function sheet(title,html){document.getElementById("sheetContent").innerHTML="<h2>"+title+"</h2>"+html;document.getElementById("sheet").showModal()}
function today(){sheet("Day 1 • Arrival & settle in",'<p class="mini-note">The Alpha template deliberately starts gently. This is a vacation, not a campaign launch.</p><div class="timeline">'+timeline.map(x=>'<div class="timeline-item"><time>'+x[0]+'</time><div><h4>'+x[1]+'</h4><p>'+x[2]+'</p></div></div>').join("")+"</div>")}
function trip(){sheet("The 8-day arc",'<div class="timeline">'+days.map(d=>'<div class="timeline-item"><time>DAY '+d[0]+'</time><div><h4>'+d[1]+'</h4><p>'+d[2]+'</p></div></div>').join("")+"</div>")}
function family(){sheet("Three travelers, one trip",'<div class="family-card"><h3>Connie • The Intentional Explorer</h3><p>Adventurous geocaching, gorgeous landscapes, snorkeling, and at least one genuine family memory. Likes a framework, not a minute-by-minute leash.</p></div><div class="family-card"><h3>Mom • The Seeker</h3><p>Relaxation first. Loves experiences, water, good food, scenic drives, a luau, and unstructured time at the resort.</p></div><div class="family-card"><h3>Brandon • The independent explorer</h3><p>Can peel off for his own interests when appropriate, then reconnect with the family for meals and shared experiences.</p></div><p class="mini-note"><strong>North Star:</strong> Different paths. Same place.</p>')}
function map(){sheet("Trip map",'<p class="mini-note">Map view is the next prototype pass. This is where real location cards and Apple Maps handoffs will live.</p>')}
function more(){sheet("Trip tools",'<div class="family-card"><h3>Reservations</h3><p>Boat trip, luau, restaurants, and other time-sensitive items.</p></div><div class="family-card"><h3>Conditions</h3><p>Weather, park access, ocean conditions, and conditional plans.</p></div><div class="family-card"><h3>Food</h3><p>Condo meals, local food trucks, restaurants, and sunset options.</p></div>')}
document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>({today,trip,map,family,more}[b.dataset.action])()));
document.getElementById("closeSheet").onclick=()=>document.getElementById("sheet").close();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));